import Header from "@/components/Header";
import "../../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fog Server",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const headersList = headers();
  // //const domain = headersList.get("host") || "";
  // const fullUrl = headersList.get("referer") || "";
  // console.log(fullUrl)
  // try {
  //   const url = new URL(fullUrl);
  //   const path = url.pathname; // Get the path from the full URL
  
  //   const isLoginPage = path === "/login";
  //   console.log(isLoginPage); // This will be true if the current page is the login page, regardless of the domain.
  // } catch (err) {
  //   console.error("Invalid URL or Referer header not provided.", err);
  // }

  return (
    <html lang="en">
      <body className={`flex flex-col ${inter.className}`}>
        <Header  />
        <div className="flex min-h-screen">
          <Navbar />
          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
